{% set name = "almosthere" %}
{% set version = "0.0.7" %}
{% set sha256 = "a8d69d855b9ca363339a0773fa7a5eb51eeadc8946b702696db01e00d32caa53" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/horta/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 3
  skip: true  # [win and vc<14]


requirements:
  build:
    - cmake
    - {{ compiler('c') }}
  host:
    - ncurses    # [not win]
  run:
    - ncurses  # [not win]

test:
  requires:
    - python  # [win]
  commands:
    - test -e $PREFIX/lib/libathr.so                    # [linux]
    - test -e $PREFIX/lib/libathr_static.a              # [linux]
    - test -e $PREFIX/lib/libathr.dylib                 # [osx]
    - test -e $PREFIX/lib/libathr_static.a              # [osx]
    - conda inspect linkages -p $PREFIX $PKG_NAME       # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME        # [osx]
    - if NOT exist %LIBRARY_PREFIX%/lib/athr.lib exit 1         # [win]
    - if NOT exist %LIBRARY_PREFIX%/bin/athr.dll exit 1         # [win]
    - if NOT exist %LIBRARY_PREFIX%/lib/athr_static.lib exit 1  # [win]

about:
  home: https://github.com/horta/almosthere
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: 'Progress indicator C library'
  description: |
    ATHR is a simple yet powerfull progress indicator library that works on
    Windows, Linux, and macOS.
  doc_url: https://github.com/horta/almosthere
  dev_url: https://github.com/horta/almosthere

extra:
  recipe-maintainers:
    - horta
