{% set name = "almosthere" %}
{% set version = "1.0.13" %}
{% set sha256 = "97db5679f488b5b5abd48446ef8b3512ecd694b7f9afc0ad1043ef5e5e8b704d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/horta/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}
    - cmake
    - ninja  # [win]
  host:
    - conda-build
    - ncurses  # [not win]
  run:
    - ncurses  # [not win]

test:
  commands:
    - test -e $PREFIX/lib/libathr.so                    # [linux]
    - test -e $PREFIX/lib/libathr.dylib                 # [osx]
    - conda inspect linkages -p $PREFIX $PKG_NAME       # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME        # [osx]
    - if NOT exist %LIBRARY_PREFIX%/lib/athr.lib exit 1         # [win]
    - if NOT exist %LIBRARY_PREFIX%/bin/athr.dll exit 1         # [win]

about:
  home: https://github.com/horta/almosthere
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Progress indicator C library
  description: |
    ATHR is a simple yet powerfull progress indicator library that works on
    Windows, Linux, and macOS.
  doc_url: https://github.com/horta/almosthere
  dev_url: https://github.com/horta/almosthere

extra:
  recipe-maintainers:
    - horta
