{% set name = "almosthere" %}
{% set version = "0.0.8" %}
{% set sha256 = "700b4b7647cd9f14f035a2e85e4c857631abfb7eef8b417f5fcd91d59877f9c1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/horta/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win and py27]
  features:
    - vc14  # [win and py35]
    - vc14  # [win and py36]


requirements:
  build:
    - toolchain  # [unix]
    - python     # [win]
    - cmake
    - ncurses    # [not win]
    - vc 14      # [win and py35]
    - vc 14      # [win and py36]
  run:
    - ncurses  # [not win]
    - vc 14    # [win and py35]
    - vc 14    # [win and py36]

test:
  requires:
    - python  # [win]
  commands:
    - test -e $PREFIX/lib/libathr.so                    # [linux]
    - test -e $PREFIX/lib/libathr_static.a              # [linux]
    - test -e $PREFIX/lib/libathr.dylib                 # [osx]
    - test -e $PREFIX/lib/libathr_static.a              # [osx]
    - conda inspect linkages -p $PREFIX $PKG_NAME       # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME        # [osx]
    - if NOT exist %LIBRARY_PREFIX%/lib/athr.lib exit 1         # [win]
    - if NOT exist %LIBRARY_PREFIX%/bin/athr.dll exit 1         # [win]
    - if NOT exist %LIBRARY_PREFIX%/lib/athr_static.lib exit 1  # [win]

about:
  home: https://github.com/horta/almosthere
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: 'Progress indicator C library'
  description: |
    ATHR is a simple yet powerfull progress indicator library that works on
    Windows, Linux, and macOS.
  doc_url: https://github.com/horta/almosthere
  dev_url: https://github.com/horta/almosthere

extra:
  recipe-maintainers:
    - horta
