{% set name = "almosthere" %}
{% set version = "3.0.3" %}
{% set sha256 = "81f5a0ef4e30e473c0a4c4fe0c84f5e3cbc30d50a2d395d9400fb10c3dcffed2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/horta/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - cmake
    - ninja  # [win]
  host:
    - conda-build
    - ncurses  # [not win]
  run:
    - ncurses  # [not win]

test:
  commands:
    - test -e $PREFIX/lib/libathr.so                     # [linux]
    - test -e $PREFIX/lib/libathr.dylib                  # [osx]
    - test -e $PREFIX/include/athr/athr.h                # [linux]
    - if NOT exist %LIBRARY_PREFIX%/lib/athr.lib exit 1  # [win]
    - if NOT exist %LIBRARY_PREFIX%/bin/athr.dll exit 1  # [win]

about:
  home: https://github.com/horta/almosthere
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Progress indicator C library
  description: |
    ATHR is a simple yet powerfull progress indicator library that works on
    Windows, Linux, and macOS.
  doc_url: https://github.com/horta/almosthere
  dev_url: https://github.com/horta/almosthere

extra:
  recipe-maintainers:
    - horta
