travis:
  secure:
    BINSTAR_TOKEN: ipFsoJczZyoCjbxCMgftYNB83+r8nShmA225Okbib1s1/fM/gGulQ7pz9p/Wzu0E7R79nwKPGqUdLwqzgBNUbhe1nuOE093nkJdsUqQWHRPPxyakGoHFx2uPDJIzEO9+SsuIaCAl1ux/tMCc41UbuMg0+oir73WUPG0FAlae1HvnDsgdGjiFf/v8Gkdc29r+uevvxmwqqy2h90y3QPwWAwu4IHgkyY9Fzjt9orYjPr/123BGJcF4fD9kbQ7HozamxeQmMdpu3NbZrZn3vpzPvlsU1ALVZHFCPL1pPZ6dS2QrcUydrXwmb7eSH5udcegEfWq+810H9/D+4BKj3U1ktxlCJjJpfpVXELkErWJkutz+7apoIxHWRDVN7imLIOgt93y1Sl5/5QaSBevXlVmG+aezem7lja4cnMv8CNzMRmc0u5rHt92YnzCX1vbqe/qqIt+E8Hd9mEG3xHor+OCF+w1SIRaOepIDUeOVFiKrHo0Dm/98EvZ9Ya4oAXFU8+XaStcFRLmGqFHnF3orVB2pxsN25jkJ1K2/sQxUWM0LFIqzqXpaMx+v6d0IyGqbKlruXI2D3+Wc0np4y59xpuk/0hRy03ye9FV28t4l0V0HzJ+a8E3DhJdgAiaWQamWAeV9o88DIYCfxGVeeSaDcb9sihKui1FY11/fhkHJqG+WWjI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
